# Generated by Django 4.1.3 on 2022-11-10 21:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Holes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('hole_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(36), django.core.validators.MinValueValidator(1)])),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1500)])),
                ('par', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_keeper.course')),
            ],
        ),
    ]
