# Generated by Django 4.1.3 on 2022-11-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_keeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='name',
        ),
    ]
