# Generated by Django 4.1.3 on 2022-11-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_keeper', '0002_rename_name_course_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holes',
            new_name='Hole',
        ),
    ]
