# Generated by Django 4.1.3 on 2022-11-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_keeper', '0003_rename_holes_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='target',
            field=models.CharField(default='', max_length=200),
        ),
    ]
