# Generated by Django 4.1.3 on 2022-11-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_keeper', '0004_hole_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='garbage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hole',
            name='hazard',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='hole',
            name='mando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hole',
            name='out_boundary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
