# Generated by Django 4.1.3 on 2022-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_keeper', '0005_hole_garbage_hole_hazard_hole_mando_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hole',
            name='hazard',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hole',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
